# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
- postgresql

#before_install:
#- psql -c 'create database tracker;' -U postgres
before_script:
  - psql -c "CREATE DATABASE tracker;" -U postgres
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -vardanmt@gmail.com
    on_success: never # default: change
    on_failure: always # default: always


env:
  global:
    - CODECOV_TOKEN=:"7e92299f-8ffd-4e7a-a960-2c93741fecb2"